name: Deployment to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Running SSH actions
        uses: appleboy/ssh-action@master
        env:
          DOCROOT: ${{ secrets.DOCROOT }}
          REPO_URL: ${{ secrets.REPO_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCROOT,REPO_URL
          script: |
            sudo apt install -y gettext git
            git -C $DOCROOT reset --hard
            git -C $DOCROOT pull || git clone --single-branch --branch main $REPO_URL $DOCROOT
            envsubst > ${DOCROOT}/.env < ${DOCROOT}/.env.example
            composer install --working-dir $DOCROOT
            php -f ${DOCROOT}/artisan migrate --force
